# Generated by Django 4.0.3 on 2022-04-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='date',
            field=models.DateField(),
        ),
    ]
