# Generated by Django 4.0.3 on 2022-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_power_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
